# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = "DevOps / Cloud Engineer portfolio for a three-tier AWS platform built with Terraform, EKS, Kubernetes, GitOps, and DevSecOps."
  author = "buicongthanh861"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true

[Languages]
[Languages.en]
title = "3-Tier AWS Platform | DevOps / Cloud Engineer"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Profile"
identifier = "GitHub Profile"
url = "https://github.com/buicongthanh861"
weight = 20

[Languages.vi]
title = "Nền tảng AWS 3-Tier | DevOps / Cloud Engineer"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Hồ sơ GitHub"
identifier = "GitHub Profile"
url = "https://github.com/buicongthanh861"
weight = 20
